# See docs/features.md for the full documentation about the blocks.

# The interval between each refresh, in milliseconds
interval = 1000

# The block to display the used memory
[[blocks]]
block = "memory"
format = "MEM {mem_used_percent}%"
#format = "MEM {mem_used} / {mem_total} {unit} ({mem_used_percent}%)"
#unit = "gibibyte"

# The block to display CPU frequency
[[blocks]]
block = "cpu_freq"
format = "CPU {freq} {unit}"
#index = 0
#unit = "ghz"
#aggregation = "average"

# The block to display CPU temperature
[[blocks]]
block = "cpu_temp"
format = "CPU {temp} {unit}"
#index = 0
#unit = "celsius"

# The block to display battery information
[[blocks]]
block = "battery"
format = "{chr_state} {rem_percent}% {rem_time}"
#index = 0

# The block to display date and time
[[blocks]]
block = "datetime"
format = "%Y-%m-%d %H:%M"